DROP TABLE IF EXISTS Players CASCADE;
DROP TABLE IF EXISTS Items CASCADE;
DROP TABLE IF EXISTS Characters CASCADE;
DROP TABLE IF EXISTS HeroesStats CASCADE;
DROP TABLE IF EXISTS ItemsStats CASCADE;
DROP TABLE IF EXISTS GeneralStats CASCADE;

CREATE TABLE IF NOT EXISTS Players (
Nickname VARCHAR(64) PRIMARY KEY,
Winrate DECIMAL(4,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS Items (
ItemName VARCHAR(64) PRIMARY KEY,
Price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Characters (
CharacterName VARCHAR(64) PRIMARY KEY,
BestPlayerNickname VARCHAR(64) NOT NULL,
FOREIGN KEY (BestPlayerNickname) REFERENCES Players(Nickname) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HeroesStats (
HeroesTop INTEGER PRIMARY KEY,
CharacterName VARCHAR(64) NOT NULL,
Winrate DECIMAL(4,3) NOT NULL,
Popularity INTEGER NOT NULL,
SelectFrequency DECIMAL(4,3) NOT NULL,
FOREIGN KEY (CharacterName) REFERENCES Characters(CharacterName) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ItemsStats (
ItemsTop INTEGER PRIMARY KEY ,
ItemName VARCHAR(64) NOT NULL,
Winrate DECIMAL(4,3) NOT NULL,
Purchases INTEGER NOT NULL,
FOREIGN KEY (ItemName) REFERENCES Items(ItemName) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GeneralStats (
StartDate TIMESTAMP PRIMARY KEY,
CharacterName VARCHAR(64) NOT NULL,
ItemName VARCHAR(64) NOT NULL,
Nickname VARCHAR(64) NOT NULL,
Winrate DECIMAL(4,3) NOT NULL,
FinishDate TIMESTAMP NOT NULL,
FOREIGN KEY (CharacterName) REFERENCES Characters(CharacterName) ON DELETE CASCADE,
FOREIGN KEY (ItemName) REFERENCES Items(ItemName) ON DELETE CASCADE,
FOREIGN KEY (Nickname) REFERENCES Players(Nickname) ON DELETE CASCADE
);